version: '3'

services:
  web:
      image: nginx:latest
      ports:
          - "8080:80"
      volumes:
          - ./code:/var/www/html
          - ./site.conf:/etc/nginx/conf.d/site.conf
      links:
          - php
  php:
      image: php:7.4-fpm
      volumes:
          - ./code:/var/www/html
